package Amazon;
import Mobiles.BB_Key_1;
import Amazon.checkout;
import Desktop.*;
import Mobiles.MainClass;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Collections;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Srinivas
 */
public class home extends javax.swing.JFrame {
    /**
     * Creates new form NewJFrame
     */
    public home() {
        setLocation(200, 200);
        initComponents();

    }
    MainClass mc = new MainClass();
public static void dt() {    
       DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");  
       LocalDateTime now = LocalDateTime.now();  
       home_date.setText(dtf.format(now));  
      }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home_date = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        cos1 = new javax.swing.JLabel();
        cos2 = new javax.swing.JLabel();
        cos3 = new javax.swing.JLabel();
        cos4 = new javax.swing.JLabel();
        cos5 = new javax.swing.JLabel();
        add1 = new javax.swing.JButton();
        add2 = new javax.swing.JButton();
        add3 = new javax.swing.JButton();
        add4 = new javax.swing.JButton();
        add5 = new javax.swing.JButton();
        com1 = new javax.swing.JComboBox<>();
        com2 = new javax.swing.JComboBox<>();
        com3 = new javax.swing.JComboBox<>();
        com4 = new javax.swing.JComboBox<>();
        com5 = new javax.swing.JComboBox<>();
        var1 = new javax.swing.JLabel();
        co1 = new javax.swing.JComboBox<>();
        l6 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nam = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jButton1 = new javax.swing.JButton();
        refresh1 = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        pname = new javax.swing.JLabel();
        qname = new javax.swing.JLabel();
        cname2 = new javax.swing.JLabel();
        p_area = new javax.swing.JTextArea();
        q_area = new javax.swing.JTextArea();
        c_area = new javax.swing.JTextArea();
        bg = new javax.swing.JLabel();
        ptotal = new javax.swing.JLabel();
        stotal = new javax.swing.JLabel();
        tictac = new javax.swing.JLabel();
        amzon = new javax.swing.JLabel();
        calc_label = new javax.swing.JLabel();
        calc = new javax.swing.JLabel();
        amzn_label = new javax.swing.JLabel();
        shut = new javax.swing.JLabel();
        tictac_label = new javax.swing.JLabel();
        wallp1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pay = new javax.swing.JLabel();
        pay_label = new javax.swing.JLabel();
        wetrans = new javax.swing.JLabel();
        wetrans_label = new javax.swing.JLabel();
        home_bg = new javax.swing.JLabel();
        dell = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(960, 572));
        setUndecorated(true);
        getContentPane().setLayout(null);

        home_date.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        home_date.setForeground(new java.awt.Color(153, 255, 255));
        home_date.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                home_dateMouseEntered(evt);
            }
        });
        getContentPane().add(home_date);
        home_date.setBounds(350, 20, 270, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/desk_topbar.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 20, 920, 20);

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setAutoscrolls(true);
        jTabbedPane1.setName(""); // NOI18N
        jTabbedPane1.setRequestFocusEnabled(false);

        jInternalFrame3.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrame3.setTitle("Amazon Home");
        jInternalFrame3.setToolTipText("");
        jInternalFrame3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jInternalFrame3.setMaximumSize(new java.awt.Dimension(100, 40));
        jInternalFrame3.setName(""); // NOI18N
        try {
            jInternalFrame3.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        jInternalFrame3.setVisible(true);
        jInternalFrame3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jInternalFrame3jInternalFrame1MouseEntered(evt);
            }
        });
        jInternalFrame3.getContentPane().setLayout(null);

        jScrollPane1.setToolTipText("");
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l1MouseClicked(evt);
            }
        });
        jPanel1.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 220, 270));
        jPanel1.add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 220, 270));
        jPanel1.add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, 220, 270));
        jPanel1.add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 760, 220, 270));
        jPanel1.add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 760, 310, 270));

        cos1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        cos1.setForeground(new java.awt.Color(153, 255, 255));
        jPanel1.add(cos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, 270, 30));

        cos2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        cos2.setForeground(new java.awt.Color(153, 255, 255));
        jPanel1.add(cos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 630, 270, 30));

        cos3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        cos3.setForeground(new java.awt.Color(153, 255, 255));
        jPanel1.add(cos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 630, 270, 30));

        cos4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        cos4.setForeground(new java.awt.Color(153, 255, 255));
        jPanel1.add(cos4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1050, 270, 30));

        cos5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        cos5.setForeground(new java.awt.Color(153, 255, 255));
        jPanel1.add(cos5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 1050, 270, 30));

        add1.setText("Add to cart");
        add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add1ActionPerformed(evt);
            }
        });
        jPanel1.add(add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 670, 150, -1));

        add2.setText("Add to cart");
        jPanel1.add(add2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 670, 150, -1));

        add3.setText("Add to cart");
        jPanel1.add(add3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 670, 150, -1));

        add4.setText("Add to cart");
        jPanel1.add(add4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 1090, 150, -1));

        add5.setText("Add to cart");
        jPanel1.add(add5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 1090, 150, -1));

        com1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jPanel1.add(com1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, -1, -1));

        com2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jPanel1.add(com2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 670, -1, -1));

        com3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jPanel1.add(com3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 670, -1, -1));

        com4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jPanel1.add(com4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1090, -1, -1));

        com5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jPanel1.add(com5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 1090, -1, -1));
        jPanel1.add(var1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, -1, -1));

        co1.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        co1.setMaximumRowCount(15);
        co1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Brand", "BlackBerry Limited", "DataWind", "Swipe", "Alactel", "BBK", "Coolpad", "Gionee", "Haier", "Honor", "Huawei", "LeEco", "Lenovo", "Motorola Mobility", "OnePlus", "Oppo", "TCL Corporation", "Vivo", "Xiaomi", "ZTE", "Nokia Corporation", "Celkon", "iball", "Intex Technologies", "Karbonn Mobiles", "Lava International", "HCL", "Jio", "LYF", "MI", "POCO", "Micromax Informatics", "Onida Electronics", "Spice X", "Spice Digital", "Videocon", "Xolo", "YU Televentures", "Panasonic", "Sansui", "Sony", "DoCoMo", "Philips", "LG", "Samsung", "Asus", "BenQ", "HTC", "Vodafone", "Apple", "Google", "HP", "InFocus", "Microsoft Mobile" }));
        co1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                co1ActionPerformed(evt);
            }
        });
        jPanel1.add(co1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 320, -1));
        co1.setFont(new java.awt.Font("Ubuntu-Regular", 0, 14));

        l6.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        l6.setForeground(new java.awt.Color(153, 255, 255));
        l6.setText("Please select brand to view available mobiles.");
        jPanel1.add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 844, 130));

        exit.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(153, 255, 255));
        exit.setText("<html> <body> <u>Exit</u> </body> </html>");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, -1, -1));

        logout.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(153, 255, 255));
        logout.setText("<html> <body> <u>LogOut</u> </body> </html>");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Pic1.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 50));

        nam.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        nam.setForeground(new java.awt.Color(153, 255, 255));
        jPanel1.add(nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 200, 30));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 255));
        jLabel3.setText("Loged in as");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Picture1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1006, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Pic4.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1010, 1100));

        jScrollPane1.setViewportView(jPanel1);

        jInternalFrame3.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 880, 450);

        jTabbedPane1.addTab("Home", jInternalFrame3);

        jInternalFrame2.setClosable(true);
        jInternalFrame2.setIconifiable(true);
        jInternalFrame2.setResizable(true);
        jInternalFrame2.setTitle("Amazon Cart");
        jInternalFrame2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jInternalFrame2.setMaximumSize(new java.awt.Dimension(100, 40));
        jInternalFrame2.setName(""); // NOI18N
        try {
            jInternalFrame2.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        jInternalFrame2.setVisible(true);
        jInternalFrame2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jInternalFrame2MouseMoved(evt);
            }
        });
        jInternalFrame2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jInternalFrame2MouseEntered(evt);
            }
        });
        jInternalFrame2.getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setText("Proceed to checkout >>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(jButton1);
        jButton1.setBounds(640, 260, 180, 23);

        refresh1.setText("Exit");
        refresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh1refreshActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(refresh1);
        refresh1.setBounds(640, 330, 180, 30);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ama_cart.png"))); // NOI18N
        jInternalFrame2.getContentPane().add(logo);
        logo.setBounds(-10, 0, 910, 100);

        pname.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        pname.setForeground(new java.awt.Color(153, 255, 255));
        pname.setText("Product Name");
        jInternalFrame2.getContentPane().add(pname);
        pname.setBounds(20, 100, 180, 30);

        qname.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        qname.setForeground(new java.awt.Color(153, 255, 255));
        qname.setText("Quantity");
        jInternalFrame2.getContentPane().add(qname);
        qname.setBounds(270, 100, 130, 30);

        cname2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        cname2.setForeground(new java.awt.Color(153, 255, 255));
        cname2.setText("Total Cost");
        jInternalFrame2.getContentPane().add(cname2);
        cname2.setBounds(470, 100, 140, 30);

        p_area.setEditable(false);
        p_area.setBackground(new java.awt.Color(51, 51, 51));
        p_area.setColumns(20);
        p_area.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        p_area.setForeground(new java.awt.Color(153, 255, 255));
        p_area.setLineWrap(true);
        p_area.setRows(5);
        p_area.setBorder(null);
        p_area.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p_area.setDragEnabled(true);
        p_area.setOpaque(false);
        jInternalFrame2.getContentPane().add(p_area);
        p_area.setBounds(30, 140, 200, 320);

        q_area.setEditable(false);
        q_area.setBackground(new java.awt.Color(51, 51, 51));
        q_area.setColumns(20);
        q_area.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        q_area.setForeground(new java.awt.Color(153, 255, 255));
        q_area.setRows(5);
        q_area.setBorder(null);
        q_area.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        q_area.setOpaque(false);
        jInternalFrame2.getContentPane().add(q_area);
        q_area.setBounds(280, 140, 90, 320);

        c_area.setEditable(false);
        c_area.setBackground(new java.awt.Color(51, 51, 51));
        c_area.setColumns(20);
        c_area.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        c_area.setForeground(new java.awt.Color(153, 255, 255));
        c_area.setRows(5);
        c_area.setBorder(null);
        c_area.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        c_area.setOpaque(false);
        jInternalFrame2.getContentPane().add(c_area);
        c_area.setBounds(480, 140, 140, 320);

        bg.setBackground(new java.awt.Color(51, 51, 51));
        bg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bg.setOpaque(true);
        jInternalFrame2.getContentPane().add(bg);
        bg.setBounds(0, 10, 940, 470);

        jTabbedPane1.addTab("Cart", jInternalFrame2);

        jTabbedPane1.setSelectedComponent(jInternalFrame3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(40, 40, 890, 500);
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        ptotal.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        ptotal.setForeground(new java.awt.Color(153, 255, 255));
        getContentPane().add(ptotal);
        ptotal.setBounds(740, 200, 140, 30);

        stotal.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        stotal.setForeground(new java.awt.Color(153, 255, 255));
        getContentPane().add(stotal);
        stotal.setBounds(740, 200, 140, 30);

        tictac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tictactoe.png"))); // NOI18N
        tictac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tictacMouseClicked(evt);
            }
        });
        getContentPane().add(tictac);
        tictac.setBounds(30, 70, 100, 80);

        amzon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Picture2.png"))); // NOI18N
        amzon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                amzonMouseClicked(evt);
            }
        });
        getContentPane().add(amzon);
        amzon.setBounds(50, 160, 130, 110);

        calc_label.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        calc_label.setForeground(new java.awt.Color(153, 255, 255));
        calc_label.setText("Calculator");
        getContentPane().add(calc_label);
        calc_label.setBounds(50, 350, 90, 40);

        calc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/calculator.png"))); // NOI18N
        calc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calcMouseClicked(evt);
            }
        });
        getContentPane().add(calc);
        calc.setBounds(40, 260, 130, 110);

        amzn_label.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        amzn_label.setForeground(new java.awt.Color(153, 255, 255));
        amzn_label.setText("Amazon");
        getContentPane().add(amzn_label);
        amzn_label.setBounds(50, 240, 70, 40);

        shut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shut.png"))); // NOI18N
        shut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shutMouseClicked(evt);
            }
        });
        getContentPane().add(shut);
        shut.setBounds(860, 460, 70, 80);

        tictac_label.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        tictac_label.setForeground(new java.awt.Color(153, 255, 255));
        tictac_label.setText("Tic Tac Toe");
        getContentPane().add(tictac_label);
        tictac_label.setBounds(50, 140, 90, 30);

        wallp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wallpaper-icon.png"))); // NOI18N
        wallp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wallp1MouseClicked(evt);
            }
        });
        getContentPane().add(wallp1);
        wallp1.setBounds(50, 380, 70, 60);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("<HTML> <HEAD> </HEAD> <BODY>Change <BR> Wallpaper </BODY> </HTML>");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 440, 80, 40);

        pay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ama_pay.png"))); // NOI18N
        pay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payMouseClicked(evt);
            }
        });
        getContentPane().add(pay);
        pay.setBounds(190, 50, 100, 90);

        pay_label.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        pay_label.setForeground(new java.awt.Color(153, 255, 255));
        pay_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pay_label.setText("Amazon Pay");
        getContentPane().add(pay_label);
        pay_label.setBounds(170, 120, 110, 40);

        wetrans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WeTransfer_logo.png"))); // NOI18N
        wetrans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wetransMouseClicked(evt);
            }
        });
        getContentPane().add(wetrans);
        wetrans.setBounds(160, 140, 110, 90);

        wetrans_label.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        wetrans_label.setForeground(new java.awt.Color(153, 255, 255));
        wetrans_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wetrans_label.setText("WeTransfer");
        wetrans_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wetrans_labelMouseClicked(evt);
            }
        });
        getContentPane().add(wetrans_label);
        wetrans_label.setBounds(170, 210, 110, 40);

        home_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall.png"))); // NOI18N
        home_bg.setText("jLabel2");
        getContentPane().add(home_bg);
        home_bg.setBounds(20, 20, 920, 520);

        dell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dellmonitor.png"))); // NOI18N
        getContentPane().add(dell);
        dell.setBounds(0, 0, 960, 572);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void shutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shutMouseClicked
        new shut().setVisible(true);
        dispose();
    }//GEN-LAST:event_shutMouseClicked

    private void amzonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amzonMouseClicked
        new Amazon.Amazn().setVisible(true);
        dispose();
    }//GEN-LAST:event_amzonMouseClicked

    private void tictacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tictacMouseClicked
        new tic().setVisible(true);
        dispose();
    }//GEN-LAST:event_tictacMouseClicked

    private void home_dateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_dateMouseEntered
dt();        // TODO add your handling code here:
    }//GEN-LAST:event_home_dateMouseEntered

    private void calcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcMouseClicked
        new Calc.calc().setVisible(true);
        dispose();
    }//GEN-LAST:event_calcMouseClicked

    private void wallp1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wallp1MouseClicked
        new wallp().setVisible(true);
        dispose();
    }//GEN-LAST:event_wallp1MouseClicked

    private void refresh1refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh1refreshActionPerformed
jTabbedPane1.hide();
    }//GEN-LAST:event_refresh1refreshActionPerformed

    private void jInternalFrame2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInternalFrame2MouseMoved
        dt();        // TODO add your handling code here:
    }//GEN-LAST:event_jInternalFrame2MouseMoved

    private void jInternalFrame2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInternalFrame2MouseEntered
        dt();        // TODO add your handling code here:
    }//GEN-LAST:event_jInternalFrame2MouseEntered
            int clicked = 0;

    private void l1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseClicked
       
    }//GEN-LAST:event_l1MouseClicked

    private void co1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_co1ActionPerformed
      add1.setVisible(true);
      add2.setVisible(true);
      add3.setVisible(true);
      add4.setVisible(true);
      add5.setVisible(true);
        if(co1.getSelectedItem()=="BlackBerry Limited")
        {
            l6.setText(null);
            
            l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BB Key1.jpg")));
            cos1.setText("Blackberry Key1, 11000");
            l2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BB.jpg")));
            cos2.setText("Blackberry, 12000");
            l3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BB Z10.jpg")));
            cos3.setText("Blackberry Z10, 11000");
            l4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BB Z3.jpg")));
            cos4.setText("Blackberry Z3, 11000");
            l5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BB key2.jpg")));
            cos5.setText("Blackberry Key2, 11000");
        }
        else if(co1.getSelectedItem()=="OnePlus")
        {
            l6.setText(null);
            l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1+ 5t.jpg")));
            cos1.setText("OnePlus 5t, 11000");
            l2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1+ 6t.jpg")));
            cos2.setText("OnePlus 6t, 15000");
            l3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/oneplus-5.jpg")));
            cos3.setText("OnePlus 5, 10000");
            l4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/oneplus-3t.jpg")));
            cos4.setText("OnePlus 3t, 9000");
            l5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/oneplus_6.png")));
            cos5.setText("OnePlus 6, 14000");
        }
        else if(co1.getSelectedItem()=="Vivo")
        {
            l6.setText(null);
            l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/vivo nex.jpg")));
            cos1.setText("Vivo Nex, 20000");
            l2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/vivo v9.jpg")));
            cos1.setText("Vivo V9, 20600");
            l3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/vivo x21.jpg")));
            cos1.setText("Vivo X21, 21000");
            l4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/vivo y83.jpg")));
            l5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/vivo_y11_pro.jpg")));
        }
        else if(co1.getSelectedItem()=="Oppo")
        {
            l6.setText(null);
            l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/oppo a7x.jpg")));
            l2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/oppo-f7.jpg")));
            l3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Oppo A3s.jpg")));
            l4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Oppo-Find-X.png")));
            l5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/vivo_y11_pro.jpg")));
        }
        else if(co1.getSelectedItem()=="Gionee")
        {
            l6.setText(null);
            l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Gionee f103.jpg")));
            l2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Gionee-P7-Max.jpg")));
            l3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gionee 9n.jpg")));
            l4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gionee-f5.jpg")));
            l5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gionee-s6s.jpg")));
        }
    }//GEN-LAST:event_co1ActionPerformed

    private void jInternalFrame3jInternalFrame1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInternalFrame3jInternalFrame1MouseEntered
        dt();        // TODO add your handling code here:
    }//GEN-LAST:event_jInternalFrame3jInternalFrame1MouseEntered

    private void payMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payMouseClicked
        new Amazon_Pay.Pay_sign().setVisible(true);
        dispose();
    }//GEN-LAST:event_payMouseClicked

    private void wetransMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wetransMouseClicked
new WeTransfer.WeTransfer().setVisible(true);
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_wetransMouseClicked

    private void wetrans_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wetrans_labelMouseClicked
new WeTransfer.WeTransfer().setVisible(true);
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_wetrans_labelMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

new checkout().setVisible(true);
    checkout.fcost.setText(stotal.getText());
    checkout.items.setText(ptotal.getText());
    checkout.var2.setText(var1.getText());
dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
  int result = JOptionPane.showConfirmDialog(this, "Logout?");        // TODO add your handling code here:
if (result == JOptionPane.YES_OPTION) {
            new Amazon.Amazn().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_logoutMouseClicked

    private void add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add1ActionPerformed
p_area.setText(null);
q_area.setText(null);
c_area.setText(null);
        switch(co1.getSelectedIndex())
{
case 1:
        if(com1.getSelectedItem() == "0")
{
    JOptionPane.showMessageDialog(this, "Please select quantity greater than 0");
    
}
else
{
    String pname="Blackberry Key 1";
int cost=11000;
int q = com1.getSelectedIndex();
int qt = q*cost;
mc.tcost=qt;
mc.ttcost += mc.tcost;
System.out.println(mc.ttcost);
mc.p_list.add(pname);
mc.q_list.add(q);
mc.c_list.add(qt);
mc.ca_list();
int sum = 0;
        for(int i = 0; i < mc.c_list.size(); i++)
        {
        sum += mc.c_list.get(i);
        home.stotal.setText(String.valueOf(sum));
        home.ptotal.setText(String.valueOf(mc.p_list.size()));
    }
    JOptionPane.showMessageDialog(this, "Added to cart");
      
}
    break;      
case  14:
    
     if(com1.getSelectedItem() == "0")
{
    JOptionPane.showMessageDialog(this, "Please select quantity greater than 0");
    
}
else
{
    String pname="OnePlus 5t";
int cost=11000;
int q = com1.getSelectedIndex();
int qt = q*cost;
mc.tcost=qt;
mc.ttcost += mc.tcost;
System.out.println(mc.ttcost);
mc.p_list.add(pname);
mc.q_list.add(q);
mc.c_list.add(qt);
mc.ca_list();
int sum = 0;
        for(int i = 0; i < mc.c_list.size(); i++)
        {
        sum += mc.c_list.get(i);
        home.stotal.setText(String.valueOf(sum));
        home.ptotal.setText(String.valueOf(mc.p_list.size()));
    }
    JOptionPane.showMessageDialog(this, "Added to cart");
        
}
      break; 
}        // TODO add your handling code here:
    }//GEN-LAST:event_add1ActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
jTabbedPane1.hide();        // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(boot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(boot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(boot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(boot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static transient javax.swing.JButton add1;
    public static transient javax.swing.JButton add2;
    public static transient javax.swing.JButton add3;
    public static transient javax.swing.JButton add4;
    public static transient javax.swing.JButton add5;
    private javax.swing.JLabel amzn_label;
    private javax.swing.JLabel amzon;
    private javax.swing.JLabel bg;
    public static transient javax.swing.JTextArea c_area;
    private javax.swing.JLabel calc;
    private javax.swing.JLabel calc_label;
    private javax.swing.JLabel cname2;
    private javax.swing.JComboBox<String> co1;
    private javax.swing.JComboBox<String> com1;
    private javax.swing.JComboBox<String> com2;
    private javax.swing.JComboBox<String> com3;
    private javax.swing.JComboBox<String> com4;
    private javax.swing.JComboBox<String> com5;
    private javax.swing.JLabel cos1;
    private javax.swing.JLabel cos2;
    private javax.swing.JLabel cos3;
    private javax.swing.JLabel cos4;
    private javax.swing.JLabel cos5;
    private javax.swing.JLabel dell;
    private javax.swing.JLabel exit;
    public static transient javax.swing.JLabel home_bg;
    public static transient javax.swing.JLabel home_date;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static transient javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logout;
    public static transient javax.swing.JLabel nam;
    public static transient javax.swing.JTextArea p_area;
    private javax.swing.JLabel pay;
    private javax.swing.JLabel pay_label;
    private javax.swing.JLabel pname;
    public static transient javax.swing.JLabel ptotal;
    public static transient javax.swing.JTextArea q_area;
    private javax.swing.JLabel qname;
    private javax.swing.JButton refresh1;
    private javax.swing.JLabel shut;
    public static transient javax.swing.JLabel stotal;
    private javax.swing.JLabel tictac;
    private javax.swing.JLabel tictac_label;
    public static transient javax.swing.JLabel var1;
    private javax.swing.JLabel wallp1;
    private javax.swing.JLabel wetrans;
    private javax.swing.JLabel wetrans_label;
    // End of variables declaration//GEN-END:variables
}
