package WeTransfer;
import Desktop.*;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Srinivas
 */
public class WeTrans_create extends javax.swing.JFrame {


        int dot_color = 0;
        Color red = new Color(255,0,0);
        Color yellow = new Color(255,255,0);
        
    /**
     * Creates new form NewJFrame
     */
    public WeTrans_create() {
        setLocation(200, 200);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        name = new javax.swing.JTextField();
        emailt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        passw = new javax.swing.JPasswordField();
        repassw = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        captchat = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        l9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        shut = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        amzon_label = new javax.swing.JLabel();
        amzon = new javax.swing.JLabel();
        calc = new javax.swing.JLabel();
        calc_label = new javax.swing.JLabel();
        top_bar = new javax.swing.JLabel();
        tictac_label = new javax.swing.JLabel();
        tictac = new javax.swing.JLabel();
        wallp = new javax.swing.JLabel();
        wallp_label = new javax.swing.JLabel();
        pay = new javax.swing.JLabel();
        pay_label = new javax.swing.JLabel();
        wetrans = new javax.swing.JLabel();
        wetrans_label = new javax.swing.JLabel();
        desk_bg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SeolaOS");
        setMinimumSize(new java.awt.Dimension(960, 572));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jInternalFrame1.getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 220, 30));
        jInternalFrame1.getContentPane().add(emailt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 220, 30));

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Email  :");
        jInternalFrame1.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Enter Password :");
        jInternalFrame1.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        passw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(passw, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 220, 30));
        jInternalFrame1.getContentPane().add(repassw, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 220, 30));

        jButton1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jButton1.setText("Create Account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, -1, -1));
        jInternalFrame1.getContentPane().add(captchat, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 130, 30));

        jLabel27.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(240, 240, 240));
        jLabel27.setText("Enter Captcha :");
        jInternalFrame1.getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));

        jButton2.setFont(new java.awt.Font("Wingdings 3", 0, 24)); // NOI18N
        jButton2.setText("⟲");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, -1, -1));

        l9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Img2.jpg"))); // NOI18N
        jInternalFrame1.getContentPane().add(l9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, -1, -1));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Your Name :");
        jInternalFrame1.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Re EnterPassword :");
        jInternalFrame1.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 255));
        jLabel3.setText("Create account");
        jInternalFrame1.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WeTrans_logo.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 500, 130));

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 510));

        getContentPane().add(jInternalFrame1);
        jInternalFrame1.setBounds(70, 30, 840, 510);

        shut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shut.png"))); // NOI18N
        shut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shutMouseClicked(evt);
            }
        });
        getContentPane().add(shut);
        shut.setBounds(860, 460, 70, 80);

        date.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        date.setForeground(new java.awt.Color(153, 255, 255));
        date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(date);
        date.setBounds(350, 20, 270, 20);

        amzon_label.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        amzon_label.setForeground(new java.awt.Color(153, 255, 255));
        amzon_label.setText("Amazon");
        getContentPane().add(amzon_label);
        amzon_label.setBounds(50, 210, 70, 40);

        amzon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Picture2.png"))); // NOI18N
        amzon.setLabelFor(amzon_label);
        amzon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                amzonMouseClicked(evt);
            }
        });
        getContentPane().add(amzon);
        amzon.setBounds(50, 130, 130, 110);

        calc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/calculator.png"))); // NOI18N
        calc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calcMouseClicked(evt);
            }
        });
        getContentPane().add(calc);
        calc.setBounds(40, 240, 130, 110);

        calc_label.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        calc_label.setForeground(new java.awt.Color(153, 255, 255));
        calc_label.setText("Calculator");
        getContentPane().add(calc_label);
        calc_label.setBounds(50, 320, 90, 40);

        top_bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/desk_topbar.png"))); // NOI18N
        getContentPane().add(top_bar);
        top_bar.setBounds(20, 20, 920, 20);

        tictac_label.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        tictac_label.setForeground(new java.awt.Color(153, 255, 255));
        tictac_label.setText("Tic Tac Toe");
        getContentPane().add(tictac_label);
        tictac_label.setBounds(50, 120, 90, 30);

        tictac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tictactoe.png"))); // NOI18N
        tictac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tictacMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tictacMousePressed(evt);
            }
        });
        getContentPane().add(tictac);
        tictac.setBounds(30, 50, 110, 90);

        wallp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wallpaper-icon.png"))); // NOI18N
        wallp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wallpMouseClicked(evt);
            }
        });
        getContentPane().add(wallp);
        wallp.setBounds(50, 380, 70, 60);

        wallp_label.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        wallp_label.setForeground(new java.awt.Color(153, 255, 255));
        wallp_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wallp_label.setText("<HTML> <HEAD> </HEAD> <BODY>Change <BR> Wallpaper </BODY> </HTML>");
        getContentPane().add(wallp_label);
        wallp_label.setBounds(50, 440, 80, 40);

        pay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ama_pay.png"))); // NOI18N
        pay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payMouseClicked(evt);
            }
        });
        getContentPane().add(pay);
        pay.setBounds(190, 50, 100, 90);

        pay_label.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        pay_label.setForeground(new java.awt.Color(153, 255, 255));
        pay_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pay_label.setText("Amazon Pay");
        getContentPane().add(pay_label);
        pay_label.setBounds(170, 120, 110, 40);

        wetrans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WeTransfer_logo.png"))); // NOI18N
        wetrans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wetransMouseClicked(evt);
            }
        });
        getContentPane().add(wetrans);
        wetrans.setBounds(160, 140, 110, 90);

        wetrans_label.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        wetrans_label.setForeground(new java.awt.Color(153, 255, 255));
        wetrans_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wetrans_label.setText("WeTransfer");
        wetrans_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wetrans_labelMouseClicked(evt);
            }
        });
        getContentPane().add(wetrans_label);
        wetrans_label.setBounds(170, 210, 110, 40);

        desk_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall.png"))); // NOI18N
        desk_bg.setText("jLabel2");
        getContentPane().add(desk_bg);
        desk_bg.setBounds(20, 20, 920, 520);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dellmonitor.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 960, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static void dt() {    
       DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");  
       LocalDateTime now = LocalDateTime.now();  
       WeTrans_create.date.setText(dtf.format(now));  
      }
    private void shutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shutMouseClicked
new shut().setVisible(true);
dispose();
    }//GEN-LAST:event_shutMouseClicked

    private void tictacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tictacMouseClicked
new tic().setVisible(true);
dispose();
    }//GEN-LAST:event_tictacMouseClicked

    private void amzonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amzonMouseClicked
new Amazon.Amazn().setVisible(true);
dispose();
    }//GEN-LAST:event_amzonMouseClicked

    private void tictacMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tictacMousePressed
      
    }//GEN-LAST:event_tictacMousePressed

    private void calcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcMouseClicked
new Calc.calc().setVisible(true);
dispose();
    }//GEN-LAST:event_calcMouseClicked

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
dt();    // TODO add your handling code here:
    }//GEN-LAST:event_formMouseMoved

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
dt();        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseEntered

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
dt();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void wallpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wallpMouseClicked
new wallp().setVisible(true); 
dispose();
    }//GEN-LAST:event_wallpMouseClicked

    private void payMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payMouseClicked
new Amazon_Pay.Pay_sign().setVisible(true);
dispose();
    }//GEN-LAST:event_payMouseClicked

    private void wetransMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wetransMouseClicked
new WeTransfer().setVisible(true);
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_wetransMouseClicked

    private void passwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwActionPerformed
public void sql()
{
    String name=WeTrans_create.name.getText();
        String email=emailt.getText();
        String pass=passw.getText();
        String repass=repassw.getText();
        String captcha=captchat.getText();
try {
                Class.forName("java.sql.DriverManager");
                Connection conn = (Connection) DriverManager.getConnection("jdbc:Mysql://localhost:3306/seolaos", "root", "Mysql@123");
                Statement st = (Statement) conn.createStatement();
                String query = "insert into wetransfer values('"+name+"', '"+email+"', '"+pass+"');";
                st.executeUpdate(query);
                JOptionPane.showMessageDialog(this, "Hurray!!\nYour account is successfully created. Log in now.");
                new WeTrans_signin().setVisible(true);
            dispose();
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dt();
        String name=WeTrans_create.name.getText();
        String email=emailt.getText();
        String pass=passw.getText();
        String repass=repassw.getText();
        String captcha=captchat.getText();
        if(!pass.equals(repass))
        {
            JOptionPane.showMessageDialog(this, "Passwords Mismatch");
            passw.setText("");
            repassw.setText("");
        }
        
        if(email.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please enter Email");
        }
        if (pass.equals(repass)
            && (captcha.equals("Gohn") || captcha.equals("Ubun") || captcha.equals("lilo")
                || captcha.equals("sfhg") || captcha.equals("kdjw") || captcha.equals("hdky")
                || captcha.equals("Ntxe") || captcha.equals("Img2") || captcha.equals("Eabs")
                || captcha.equals("Kpno")
                &&!email.equals("")))
        {
            sql();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Incorrect Captcha, Try again");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dt();
        double n1=Math.random();
        int n2=(int)(n1*10);
        if(n2==1)
        {
            l9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Img1.jpg")));
        }
        if(n2==2)
        {
            l9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Img2.jpg")));
        }
        if(n2==3)
        {
            l9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Img3.jpg")));
        }
        if(n2==4)
        {
            l9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Img4.jpg")));
        }
        if(n2==5)
        {
            l9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Img5.jpg")));
        }
        if(n2==6)
        {
            l9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Img6.jpg")));
        }
        if(n2==7)
        {
            l9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Img7.jpg")));
        }
        if(n2==8)
        {
            l9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Img8.jpg")));
        }
        if(n2==9)
        {
            l9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Img9.jpg")));
        }
        if(n2==0)
        {
            l9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Img10.jpg")));
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void wetrans_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wetrans_labelMouseClicked
new WeTransfer().setVisible(true);
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_wetrans_labelMouseClicked


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(boot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(boot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(boot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(boot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WeTrans_create().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amzon;
    private javax.swing.JLabel amzon_label;
    private javax.swing.JLabel calc;
    private javax.swing.JLabel calc_label;
    private javax.swing.JTextField captchat;
    public static transient javax.swing.JLabel date;
    public static transient javax.swing.JLabel desk_bg;
    private javax.swing.JTextField emailt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel l9;
    public static transient javax.swing.JTextField name;
    private javax.swing.JPasswordField passw;
    private javax.swing.JLabel pay;
    private javax.swing.JLabel pay_label;
    private javax.swing.JPasswordField repassw;
    private javax.swing.JLabel shut;
    private javax.swing.JLabel tictac;
    private javax.swing.JLabel tictac_label;
    private javax.swing.JLabel top_bar;
    private javax.swing.JLabel wallp;
    private javax.swing.JLabel wallp_label;
    private javax.swing.JLabel wetrans;
    private javax.swing.JLabel wetrans_label;
    // End of variables declaration//GEN-END:variables
}