package Desktop;
import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import Amazon.*;
import Calc.calc;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Srinivas
 */
public class wallp extends javax.swing.JFrame {


        int dot_color = 0;
        Color red= new Color(255,0,0);
        Color yellow= new Color(255,255,0);
        
    /**
     * Creates new form NewJFrame
     */
    public wallp() {
        setLocation(200, 200);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        cb1 = new javax.swing.JComboBox<>();
        sample = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        shut = new javax.swing.JLabel();
        wallp_date = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        amzon = new javax.swing.JLabel();
        calc = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        top_bar = new javax.swing.JLabel();
        tictac_label = new javax.swing.JLabel();
        tictac = new javax.swing.JLabel();
        wallp = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pay = new javax.swing.JLabel();
        pay_label = new javax.swing.JLabel();
        wetrans = new javax.swing.JLabel();
        wetrans_label = new javax.swing.JLabel();
        wall_bg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(960, 572));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jInternalFrame1.setBackground(new java.awt.Color(51, 51, 51));
        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setTitle("Change Wallpaper");
        jInternalFrame1.setToolTipText("");
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        cb1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wallpaper 1", "Wallpaper 2", "Wallpaper 3", "Wallpaper 4", "Wallpaper 5" }));
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(cb1);
        cb1.setBounds(70, 10, 305, 30);

        sample.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(sample);
        sample.setBounds(40, 50, 720, 370);

        jButton1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton1.setText("Change Wallpaper");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton1);
        jButton1.setBounds(490, 10, 270, 30);

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 440);

        getContentPane().add(jInternalFrame1);
        jInternalFrame1.setBounds(90, 50, 810, 470);

        shut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shut.png"))); // NOI18N
        shut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shutMouseClicked(evt);
            }
        });
        getContentPane().add(shut);
        shut.setBounds(860, 460, 70, 80);

        wallp_date.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        wallp_date.setForeground(new java.awt.Color(153, 255, 255));
        wallp_date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wallp_date.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                wallp_dateMouseEntered(evt);
            }
        });
        getContentPane().add(wallp_date);
        wallp_date.setBounds(350, 20, 270, 20);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 255));
        jLabel6.setText("Amazon");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 210, 70, 40);

        amzon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Picture2.png"))); // NOI18N
        amzon.setLabelFor(jLabel6);
        amzon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                amzonMouseClicked(evt);
            }
        });
        getContentPane().add(amzon);
        amzon.setBounds(50, 130, 130, 110);

        calc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/calculator.png"))); // NOI18N
        calc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calcMouseClicked(evt);
            }
        });
        getContentPane().add(calc);
        calc.setBounds(40, 240, 130, 110);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 255, 255));
        jLabel7.setText("Calculator");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 320, 90, 40);

        top_bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/desk_topbar.png"))); // NOI18N
        getContentPane().add(top_bar);
        top_bar.setBounds(20, 20, 920, 20);

        tictac_label.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        tictac_label.setForeground(new java.awt.Color(153, 255, 255));
        tictac_label.setText("Tic Tac Toe");
        getContentPane().add(tictac_label);
        tictac_label.setBounds(50, 120, 90, 30);

        tictac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tictactoe.png"))); // NOI18N
        tictac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tictacMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tictacMousePressed(evt);
            }
        });
        getContentPane().add(tictac);
        tictac.setBounds(30, 50, 110, 90);

        wallp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wallpaper-icon.png"))); // NOI18N
        wallp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wallpMouseClicked(evt);
            }
        });
        getContentPane().add(wallp);
        wallp.setBounds(50, 380, 70, 60);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("<HTML> <HEAD> </HEAD> <BODY>Change <BR> Wallpaper </BODY> </HTML>");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 440, 80, 40);

        pay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ama_pay.png"))); // NOI18N
        pay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payMouseClicked(evt);
            }
        });
        getContentPane().add(pay);
        pay.setBounds(190, 50, 100, 90);

        pay_label.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        pay_label.setForeground(new java.awt.Color(153, 255, 255));
        pay_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pay_label.setText("Amazon Pay");
        getContentPane().add(pay_label);
        pay_label.setBounds(170, 120, 110, 40);

        wetrans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WeTransfer_logo.png"))); // NOI18N
        wetrans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wetransMouseClicked(evt);
            }
        });
        getContentPane().add(wetrans);
        wetrans.setBounds(160, 140, 110, 90);

        wetrans_label.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        wetrans_label.setForeground(new java.awt.Color(153, 255, 255));
        wetrans_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wetrans_label.setText("WeTransfer");
        wetrans_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wetrans_labelMouseClicked(evt);
            }
        });
        getContentPane().add(wetrans_label);
        wetrans_label.setBounds(170, 210, 110, 40);

        wall_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall.png"))); // NOI18N
        wall_bg.setText("jLabel2");
        getContentPane().add(wall_bg);
        wall_bg.setBounds(20, 20, 920, 520);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dellmonitor.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 960, 580);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 960, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static void dt() {    
       DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");  
       LocalDateTime now = LocalDateTime.now();  
       wallp_date.setText(dtf.format(now));  
      }
    private void shutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shutMouseClicked
new shut().setVisible(true);
dispose();
    }//GEN-LAST:event_shutMouseClicked

    private void tictacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tictacMouseClicked
new tic().setVisible(true);
dispose();
    }//GEN-LAST:event_tictacMouseClicked

    private void amzonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amzonMouseClicked
new Amazon.Amazn().setVisible(true);
dispose();
    }//GEN-LAST:event_amzonMouseClicked

    private void tictacMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tictacMousePressed
      
    }//GEN-LAST:event_tictacMousePressed

    private void calcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcMouseClicked
new Calc.calc().setVisible(true);
dispose();
    }//GEN-LAST:event_calcMouseClicked

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
dt();    // TODO add your handling code here:
    }//GEN-LAST:event_formMouseMoved

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
dt();        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseEntered

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
dt();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void wallpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wallpMouseClicked
new wallp().setVisible(true);
    }//GEN-LAST:event_wallpMouseClicked

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
if(cb1.getSelectedItem() == "Wallpaper 1")
{
    sample.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall.png"))); // NOI18N
}
if(cb1.getSelectedItem() == "Wallpaper 2")
{
    sample.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall2.jpg"))); // NOI18N
}
if(cb1.getSelectedItem() == "Wallpaper 3")
{
    sample.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall3.jpg"))); // NOI18N
}
if(cb1.getSelectedItem() == "Wallpaper 4")
{
    sample.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall4.png"))); // NOI18N
}
if(cb1.getSelectedItem() == "Wallpaper 5")
{
    sample.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall5.jpg"))); // NOI18N
}
    }//GEN-LAST:event_cb1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(cb1.getSelectedItem() == "Wallpaper 1")
{
    wall_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall.png")));
    Amazon.Amazn.amazn_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall.png")));
    Amazon.Sign_in.sin_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall.png")));
    Amazon.Create_acc.create_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall.png")));
    Amazon.home.home_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall.png")));
    Amazon.home_sign.sin_home_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall.png")));
    Calc.calc.calc_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall.png")));
    tic.tic_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall.png")));
    desk.desk_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall.png")));// NOI18N // NOI18N
}
if(cb1.getSelectedItem() == "Wallpaper 2")
{
    wall_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall2.jpg")));
    Amazon.Amazn.amazn_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall2.jpg")));
    Amazon.Sign_in.sin_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall2.jpg")));
    Amazon.Create_acc.create_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall2.jpg")));
    Amazon.home.home_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall2.jpg")));
    Amazon.home_sign.sin_home_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall2.jpg")));
    Calc.calc.calc_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall2.jpg")));
    tic.tic_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall2.jpg")));
    desk.desk_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall2.jpg")));// NOI18N // NOI18N
}
if(cb1.getSelectedItem() == "Wallpaper 3")
{
    wall_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall3.jpg")));
    Amazon.Amazn.amazn_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall3.jpg")));
    Amazon.Sign_in.sin_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall3.jpg")));
    Amazon.Create_acc.create_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall3.jpg")));
    Amazon.home.home_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall3.jpg")));
    Amazon.home_sign.sin_home_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall3.jpg")));
    Calc.calc.calc_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall3.jpg")));
    tic.tic_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall3.jpg")));
    desk.desk_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall3.jpg")));// NOI18N // NOI18N
}
if(cb1.getSelectedItem() == "Wallpaper 4")
{
    wall_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall4.png")));
    Amazon.Amazn.amazn_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall4.png")));
    Amazon.Sign_in.sin_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall4.png")));
    Amazon.Create_acc.create_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall4.png")));
    Amazon.home.home_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall4.png")));
    Amazon.home_sign.sin_home_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall4.png")));
    Calc.calc.calc_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall4.png")));
    tic.tic_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall4.png")));
    desk.desk_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall4.png")));// NOI18N // NOI18N
}
if(cb1.getSelectedItem() == "Wallpaper 5")
{
    wall_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall5.jpg")));
    Amazon.Amazn.amazn_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall5.jpg")));
    Amazon.Sign_in.sin_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall5.jpg")));
    Amazon.Create_acc.create_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall5.jpg")));
    Amazon.home.home_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall5.jpg")));
    Amazon.home_sign.sin_home_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall5.jpg")));
    Calc.calc.calc_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall5.jpg")));
    tic.tic_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall5.jpg")));
    desk.desk_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall5.jpg")));// NOI18N // NOI18N
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void wallp_dateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wallp_dateMouseEntered
dt();        // TODO add your handling code here:
    }//GEN-LAST:event_wallp_dateMouseEntered

    private void payMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payMouseClicked
        new Amazon_Pay.Pay_sign().setVisible(true);
        dispose();
    }//GEN-LAST:event_payMouseClicked

    private void wetransMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wetransMouseClicked
new WeTransfer.WeTransfer().setVisible(true);
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_wetransMouseClicked

    private void wetrans_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wetrans_labelMouseClicked
new WeTransfer.WeTransfer().setVisible(true);
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_wetrans_labelMouseClicked


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(boot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(boot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(boot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(boot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new wallp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amzon;
    private javax.swing.JLabel calc;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pay;
    private javax.swing.JLabel pay_label;
    private javax.swing.JLabel sample;
    private javax.swing.JLabel shut;
    private javax.swing.JLabel tictac;
    private javax.swing.JLabel tictac_label;
    private javax.swing.JLabel top_bar;
    private javax.swing.JLabel wall_bg;
    private javax.swing.JLabel wallp;
    public static transient javax.swing.JLabel wallp_date;
    private javax.swing.JLabel wetrans;
    private javax.swing.JLabel wetrans_label;
    // End of variables declaration//GEN-END:variables
}