package Desktop;


import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Srinivas
 */
public class tic extends javax.swing.JFrame {
        int dot_color = 0;
        int dot_color2 = 0;
        Color red= new Color(255,0,0);
        Color yellow= new Color(255,255,0);
    /**
     * Creates new form NewJFrame
     */
    public tic() {
        setLocation(200, 200);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Tic_date = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        out = new javax.swing.JLabel();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tictac = new javax.swing.JLabel();
        amzon = new javax.swing.JLabel();
        calc_label = new javax.swing.JLabel();
        calc = new javax.swing.JLabel();
        amzon_label = new javax.swing.JLabel();
        shut = new javax.swing.JLabel();
        tictac_label = new javax.swing.JLabel();
        wallp = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pay = new javax.swing.JLabel();
        pay_label = new javax.swing.JLabel();
        wetrans = new javax.swing.JLabel();
        wetrans_label = new javax.swing.JLabel();
        tic_bg = new javax.swing.JLabel();
        dell = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(960, 572));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        getContentPane().setLayout(null);

        Tic_date.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Tic_date.setForeground(new java.awt.Color(153, 255, 255));
        getContentPane().add(Tic_date);
        Tic_date.setBounds(350, 20, 270, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/desk_topbar.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 20, 920, 20);

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setResizable(true);
        jInternalFrame1.setTitle("Tic-Tac-Toe");
        jInternalFrame1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jInternalFrame1.setMaximumSize(new java.awt.Dimension(100, 40));
        jInternalFrame1.setName(""); // NOI18N
        try {
            jInternalFrame1.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        jInternalFrame1.setVisible(true);
        jInternalFrame1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jInternalFrame1MouseMoved(evt);
            }
        });
        jInternalFrame1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jInternalFrame1MouseEntered(evt);
            }
        });
        jInternalFrame1.getContentPane().setLayout(null);

        buttonGroup1.add(rb1);
        rb1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        rb1.setForeground(new java.awt.Color(153, 255, 255));
        rb1.setText("Player 1");
        rb1.setOpaque(false);
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(rb1);
        rb1.setBounds(480, 190, 140, 24);

        buttonGroup1.add(rb2);
        rb2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        rb2.setForeground(new java.awt.Color(153, 255, 255));
        rb2.setLabel("Player 2");
        rb2.setOpaque(false);
        jInternalFrame1.getContentPane().add(rb2);
        rb2.setBounds(480, 230, 140, 37);

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 255, 255));
        jButton1.setText("Reset");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 255, 255)));
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton1);
        jButton1.setBounds(470, 360, 180, 40);

        out.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        out.setForeground(new java.awt.Color(153, 255, 255));
        jInternalFrame1.getContentPane().add(out);
        out.setBounds(360, 50, 420, 70);

        bt1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        bt1.setForeground(new java.awt.Color(153, 255, 255));
        bt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt1.setBorderPainted(false);
        bt1.setContentAreaFilled(false);
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(bt1);
        bt1.setBounds(0, 110, 110, 90);

        bt2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        bt2.setForeground(new java.awt.Color(153, 255, 255));
        bt2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt2.setBorderPainted(false);
        bt2.setContentAreaFilled(false);
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(bt2);
        bt2.setBounds(130, 110, 160, 90);

        bt3.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        bt3.setForeground(new java.awt.Color(153, 255, 255));
        bt3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt3.setBorderPainted(false);
        bt3.setContentAreaFilled(false);
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(bt3);
        bt3.setBounds(310, 110, 120, 90);

        bt4.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        bt4.setForeground(new java.awt.Color(153, 255, 255));
        bt4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt4.setBorderPainted(false);
        bt4.setContentAreaFilled(false);
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(bt4);
        bt4.setBounds(0, 210, 110, 150);

        bt5.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        bt5.setForeground(new java.awt.Color(153, 255, 255));
        bt5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt5.setBorderPainted(false);
        bt5.setContentAreaFilled(false);
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(bt5);
        bt5.setBounds(130, 210, 160, 150);

        bt6.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        bt6.setForeground(new java.awt.Color(153, 255, 255));
        bt6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt6.setBorderPainted(false);
        bt6.setContentAreaFilled(false);
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(bt6);
        bt6.setBounds(300, 210, 120, 150);

        bt7.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        bt7.setForeground(new java.awt.Color(153, 255, 255));
        bt7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt7.setBorderPainted(false);
        bt7.setContentAreaFilled(false);
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(bt7);
        bt7.setBounds(0, 370, 120, 100);

        bt8.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        bt8.setForeground(new java.awt.Color(153, 255, 255));
        bt8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt8.setBorderPainted(false);
        bt8.setContentAreaFilled(false);
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(bt8);
        bt8.setBounds(130, 370, 160, 100);

        bt9.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        bt9.setForeground(new java.awt.Color(153, 255, 255));
        bt9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt9.setBorderPainted(false);
        bt9.setContentAreaFilled(false);
        bt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt9ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(bt9);
        bt9.setBounds(300, 370, 130, 100);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 255));
        jLabel6.setText("Tic-Tac-Toe");
        jInternalFrame1.getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 10, 290, 70);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tict.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 100, 426, 370);

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setOpaque(true);
        jInternalFrame1.getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 900, 640);

        getContentPane().add(jInternalFrame1);
        jInternalFrame1.setBounds(130, 40, 680, 500);

        tictac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tictactoe.png"))); // NOI18N
        tictac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tictacMouseClicked(evt);
            }
        });
        getContentPane().add(tictac);
        tictac.setBounds(30, 70, 100, 80);

        amzon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Picture2.png"))); // NOI18N
        amzon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                amzonMouseClicked(evt);
            }
        });
        getContentPane().add(amzon);
        amzon.setBounds(50, 160, 130, 110);

        calc_label.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        calc_label.setForeground(new java.awt.Color(153, 255, 255));
        calc_label.setText("Calculator");
        getContentPane().add(calc_label);
        calc_label.setBounds(50, 350, 90, 40);

        calc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/calculator.png"))); // NOI18N
        calc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calcMouseClicked(evt);
            }
        });
        getContentPane().add(calc);
        calc.setBounds(40, 260, 130, 110);

        amzon_label.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        amzon_label.setForeground(new java.awt.Color(153, 255, 255));
        amzon_label.setText("Amazon");
        getContentPane().add(amzon_label);
        amzon_label.setBounds(50, 240, 70, 40);

        shut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shut.png"))); // NOI18N
        shut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shutMouseClicked(evt);
            }
        });
        getContentPane().add(shut);
        shut.setBounds(860, 460, 70, 80);

        tictac_label.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        tictac_label.setForeground(new java.awt.Color(153, 255, 255));
        tictac_label.setText("Tic Tac Toe");
        getContentPane().add(tictac_label);
        tictac_label.setBounds(50, 140, 90, 30);

        wallp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wallpaper-icon.png"))); // NOI18N
        wallp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wallpMouseClicked(evt);
            }
        });
        getContentPane().add(wallp);
        wallp.setBounds(50, 380, 70, 60);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("<HTML> <HEAD> </HEAD> <BODY>Change <BR> Wallpaper </BODY> </HTML>");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 440, 80, 40);

        pay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ama_pay.png"))); // NOI18N
        pay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payMouseClicked(evt);
            }
        });
        getContentPane().add(pay);
        pay.setBounds(190, 50, 100, 90);

        pay_label.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        pay_label.setForeground(new java.awt.Color(153, 255, 255));
        pay_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pay_label.setText("Amazon Pay");
        getContentPane().add(pay_label);
        pay_label.setBounds(170, 120, 110, 40);

        wetrans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WeTransfer_logo.png"))); // NOI18N
        wetrans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wetransMouseClicked(evt);
            }
        });
        getContentPane().add(wetrans);
        wetrans.setBounds(160, 140, 110, 90);

        wetrans_label.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        wetrans_label.setForeground(new java.awt.Color(153, 255, 255));
        wetrans_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wetrans_label.setText("WeTransfer");
        wetrans_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wetrans_labelMouseClicked(evt);
            }
        });
        getContentPane().add(wetrans_label);
        wetrans_label.setBounds(170, 210, 110, 40);

        tic_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seola_wall.png"))); // NOI18N
        tic_bg.setText("jLabel2");
        getContentPane().add(tic_bg);
        tic_bg.setBounds(20, 20, 920, 520);

        dell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dellmonitor.png"))); // NOI18N
        getContentPane().add(dell);
        dell.setBounds(0, 0, 960, 572);

        pack();
    }// </editor-fold>//GEN-END:initComponents
void disble() {
        bt1.setEnabled(false);
        bt2.setEnabled(false);
        bt3.setEnabled(false);
        bt4.setEnabled(false);
        bt5.setEnabled(false);
        bt6.setEnabled(false);
        bt7.setEnabled(false);
        bt8.setEnabled(false);
        bt9.setEnabled(false);
    }

    void verify() {
        if (bt1.getText().equals("X") && bt2.getText().equals("X") && bt3.getText().equals("X")) {
            out.setText("Player 1 Wins!!");
            disble();
            draw2();

        }
        if (bt4.getText().equals("X") && bt5.getText().equals("X") && bt6.getText().equals("X")) {
            out.setText("Player 1 Wins!!");
            disble();
            draw2();
        }
        if (bt7.getText().equals("X") && bt8.getText().equals("X") && bt9.getText().equals("X")) {
            out.setText("Player 1 Wins!!");
            disble();
            draw2();
        }
        if (bt1.getText().equals("X") && bt4.getText().equals("X") && bt7.getText().equals("X")) {
            out.setText("Player 1 Wins!!");
            disble();
            draw2();
        }
        if (bt2.getText().equals("X") && bt5.getText().equals("X") && bt8.getText().equals("X")) {
            out.setText("Player 1 Wins!!");
            disble();
            draw2();
        }
        if (bt3.getText().equals("X") && bt6.getText().equals("X") && bt9.getText().equals("X")) {
            out.setText("Player 1 Wins!!");
            disble();
            draw2();
        }
        if (bt1.getText().equals("X") && bt5.getText().equals("X") && bt9.getText().equals("X")) {
            out.setText("Player 1 Wins!!");
            disble();
            draw2();
        }
        if (bt3.getText().equals("X") && bt5.getText().equals("X") && bt7.getText().equals("X")) {
            out.setText("Player 1 Wins!!");
            disble();
            draw2();
        }
        if (bt1.getText().equals("O") && bt2.getText().equals("O") && bt3.getText().equals("O")) {
            out.setText("Player 2 Wins!!");
            disble();
            draw2();
        }
        if (bt4.getText().equals("O") && bt5.getText().equals("O") && bt6.getText().equals("O")) {
            out.setText("Player 2 Wins!!");
            disble();
            draw2();
        }
        if (bt7.getText().equals("O") && bt8.getText().equals("O") && bt9.getText().equals("O")) {
            out.setText("Player 2 Wins!!");
            disble();
            draw2();
        }
        if (bt1.getText().equals("O") && bt4.getText().equals("O") && bt7.getText().equals("O")) {
            out.setText("Player 2 Wins!!");
            disble();
            draw2();
        }
        if (bt2.getText().equals("O") && bt5.getText().equals("O") && bt8.getText().equals("O")) {
            out.setText("Player 2 Wins!!");
            disble();
            draw2();
        }
        if (bt3.getText().equals("O") && bt6.getText().equals("O") && bt9.getText().equals("O")) {
            out.setText("Player 2 Wins!!");
            disble();
            draw2();
        }
        if (bt1.getText().equals("O") && bt5.getText().equals("O") && bt9.getText().equals("O")) {
            out.setText("Player 2 Wins!!");
            disble();
            draw2();
        }
        if (bt3.getText().equals("O") && bt5.getText().equals("O") && bt7.getText().equals("O")) {
            out.setText("Player 2 Wins!!");
            disble();
            draw2();
        }

    }

    void draw1() {
        {
            if (rb1.isSelected()) {
                rb1.setSelected(false);
                rb2.setSelected(true);
            } else if (rb2.isSelected()) {
                rb2.setSelected(false);
                rb1.setSelected(true);
            }
        }
        if (bt1.isSelected() && bt2.isSelected() && bt3.isSelected() && bt4.isSelected() && bt5.isSelected() && bt6.isSelected() && bt7.isSelected() && bt8.isSelected() && bt9.isSelected()) {
            out.setText("Draw match... Reset to continue");
        }
    }

    void draw2() {
        if (bt1.isSelected() && bt2.isSelected() && bt3.isSelected() && bt4.isSelected() && bt5.isSelected() && bt6.isSelected() && bt7.isSelected() && bt8.isSelected() && bt9.isSelected()) {
            out.setText("Draw match... Reset to continue");
        }
    }
    public static void dt() {    
       DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");  
       LocalDateTime now = LocalDateTime.now();  
       Tic_date.setText(dtf.format(now));  
      }
    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        bt1.setText("");
        bt1.setEnabled(true);
        bt2.setText("");
        bt2.setEnabled(true);
        bt3.setText("");
        bt3.setEnabled(true);
        bt4.setText("");
        bt4.setEnabled(true);
        bt5.setText("");
        bt5.setEnabled(true);
        bt6.setText("");
        bt6.setEnabled(true);
        bt7.setText("");
        bt7.setEnabled(true);
        bt8.setText("");
        bt8.setEnabled(true);
        bt9.setText("");
        bt9.setEnabled(true);
        rb1.setSelected(true);
        rb2.setSelected(false);
        out.setText(null);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
dt();
        if (rb1.isSelected()) {
            bt9.setText("X");
        } 
        else if (rb2.isSelected()) {
            bt9.setText("O");
        }
        verify();
        bt9.setEnabled(false);
        draw1();
        draw2();        
    }//GEN-LAST:event_bt9ActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
dt();
        if (rb1.isSelected()) {
            bt7.setText("X");
        } // TODO add your handling code here:
        else if (rb2.isSelected()) {
            bt7.setText("O");
        }
        verify();
        bt7.setEnabled(false);
        draw1();
        draw2();                // TODO add your handling code here:
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
dt();
        if (rb1.isSelected()) {
            bt1.setText("X");
        } else if (rb2.isSelected()) {
            bt1.setText("O");
        }
        verify();
        bt1.setEnabled(false);
        draw1();
        draw2();                // TODO add your handling code here:
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
dt();
        if (rb1.isSelected()) {
            bt6.setText("X");
        } // TODO add your handling code here:
        else if (rb2.isSelected()) {
            bt6.setText("O");
        }
        verify();
        bt6.setEnabled(false);
        draw1();
        draw2();
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
dt();
        if (rb1.isSelected()) {
            bt8.setText("X");
        } // TODO add your handling code here:
        else if (rb2.isSelected()) {
            bt8.setText("O");
        }
        verify();
        bt8.setEnabled(false);
        draw1();
        draw2();
    }//GEN-LAST:event_bt8ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
dt();
        if (rb1.isSelected()) {
            bt3.setText("X");
        } 
        else if (rb2.isSelected()) {
            bt3.setText("O");
        }
        verify();
        bt3.setEnabled(false);
        draw1();
        draw2();
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
dt();
        if (rb1.isSelected()) {
            bt4.setText("X");
        } 
        else if (rb2.isSelected()) {
            if (rb1.isSelected()) {
                rb1.setSelected(false);
                rb2.setSelected(true);
            }

            bt4.setText("O");
        }
        verify();
        bt4.setEnabled(false);
        draw1();
        draw2();
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
dt();
        if (rb1.isSelected()) {
            bt5.setText("X");
        } // TODO add your handling code here:
        else if (rb2.isSelected()) {
            bt5.setText("O");
        }
        verify();
        bt5.setEnabled(false);
        draw1();
        draw2();
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
dt();
        if (rb1.isSelected()) {
            bt2.setText("X");
        } // TODO add your handling code here:
        else if (rb2.isSelected()) {
            bt2.setText("O");
        }
        verify();
        bt2.setEnabled(false);
        draw1();
        draw2();
    }//GEN-LAST:event_bt2ActionPerformed

    private void tictacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tictacMouseClicked
        new tic().setVisible(true);
        dispose();
    }//GEN-LAST:event_tictacMouseClicked

    private void shutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shutMouseClicked
        new shut().setVisible(true);
        dispose();
    }//GEN-LAST:event_shutMouseClicked

    private void amzonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amzonMouseClicked
        new Amazon.Amazn().setVisible(true);
        dispose();
    }//GEN-LAST:event_amzonMouseClicked

    private void calcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcMouseClicked
        new Calc.calc().setVisible(true);
        dispose();
    }//GEN-LAST:event_calcMouseClicked

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
dt();        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseEntered

    private void jInternalFrame1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInternalFrame1MouseEntered
dt();        // TODO add your handling code here:
    }//GEN-LAST:event_jInternalFrame1MouseEntered

    private void jInternalFrame1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInternalFrame1MouseMoved
dt();        // TODO add your handling code here:
    }//GEN-LAST:event_jInternalFrame1MouseMoved

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
dt();        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseMoved

    private void wallpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wallpMouseClicked
        new wallp().setVisible(true);
        dispose();
    }//GEN-LAST:event_wallpMouseClicked

    private void payMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payMouseClicked
        new Amazon_Pay.Pay_sign().setVisible(true);
        dispose();
    }//GEN-LAST:event_payMouseClicked

    private void wetransMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wetransMouseClicked
new WeTransfer.WeTransfer().setVisible(true);
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_wetransMouseClicked

    private void wetrans_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wetrans_labelMouseClicked
new WeTransfer.WeTransfer().setVisible(true);
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_wetrans_labelMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(boot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(boot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(boot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(boot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static transient javax.swing.JLabel Tic_date;
    private javax.swing.JLabel amzon;
    private javax.swing.JLabel amzon_label;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel calc;
    private javax.swing.JLabel calc_label;
    private javax.swing.JLabel dell;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel out;
    private javax.swing.JLabel pay;
    private javax.swing.JLabel pay_label;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JLabel shut;
    public static transient javax.swing.JLabel tic_bg;
    private javax.swing.JLabel tictac;
    private javax.swing.JLabel tictac_label;
    private javax.swing.JLabel wallp;
    private javax.swing.JLabel wetrans;
    private javax.swing.JLabel wetrans_label;
    // End of variables declaration//GEN-END:variables
}
